
from .ammeters import PZA_DRIVERS_LIST as AMMETERS_DRIVERS
from .voltmeters import PZA_DRIVERS_LIST as VOLTMETERS_DRIVERS

from .psu import PZA_DRIVERS_LIST as PSU_DRIVERS

from .dio import PZA_DRIVERS_LIST as DIO_DRIVERS
from .platform import PZA_DRIVERS_LIST as PLATFORM_DRIVERS

PZA_DRIVERS_LIST= [] \
    + DIO_DRIVERS \
    + AMMETERS_DRIVERS \
    + PSU_DRIVERS \
    + VOLTMETERS_DRIVERS \
    + PLATFORM_DRIVERS

