from behave import *

@given('a reactor connected on a test platform')
def step_given(context):
    pass

@then('the status attribute must indicate an error for one instance')
def step_then(context):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass

@then('the status attribute must indicate running for all instances')
def step_then(context):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass

@then('the notification attribute must indicate no alert')
def step_then(context):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass

@then('the notification attribute must indicate an alert for this instance')
def step_then(context):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass