from behave import *


@given('a reactor trying to connect to an invalid platform')
def step_impl(context):
    pass


@given('the boolean attribute rw {string}')
def step_given(context, string):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass

@given('the boolean attribute wo {string}')
def step_given(context, string):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass

@given('the boolean attribute ro {string}')
def step_given(context, string):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass

use_step_matcher("re")
@when('I set rw boolean to (true|false)')
def step_when(context, value):
    pass

@when('I set wo boolean to (true|false)')
def step_when(context, value):
    pass

@then('the rw boolean value is (true|false)')
def step_then(context, value):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass

@then('the ro boolean value is (true|false)')
def step_then(context, value):
    # This was autogenerated using Cucumber Expressions syntax.
    # Please convert to use Regular Expressions, as Behave does not currently support Cucumber Expressions.
    pass
