name: Basic Tests
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # ---
      - name: Debug
        run: ls -la .

      # ---
      - run: apt-get update
      - run: apt-get install -y mosquitto git
      - run: apt-get install -y python3 python3-pip

      # ---
      - run: pip install -r ./tests/requirements.txt
      - run: pip install -r ./platform/requirements.txt
      - run: pip install ./client/
      - run: pip install ./platform/

      # Build Docker image with Buildx
      - name: Build and push Docker image panduza-py-platform
        # id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: platform
          tags: test-image:latest
          push: false

      # ---
      - run: pzadmin --init test_hunt_directory
      # - run: pzadmin --hunt test_hunt_directory # need docker, should be tested with an other method

      - uses: addnab/docker-run-action@v3
        with:
          context: platform
          image: test-image:latest

      # ---
      - run: mosquitto -d

      # ---
      - run: python3 ./platform/deploy/pza-py-platform-run.py ./tests/pza/tree.json &

      # ---
      - name: Execute tests
        working-directory: tests
        run: robot robot/*

      # ---
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-report
          path: tests/

      # ---
      - run: echo "🎉 Basic Tests finished !"

